version: "3"

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:29092,kafka2:39092,kafka3:49092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/log:/var/lib/zookeeper/log
  kafka1:
    image: confluentinc/cp-kafka
    hostname: kafka1
    depends_on:
      - zookeeper
    restart: "no"
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./kafka/1/data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092,INTERNET://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:29092,EXTERNAL://10.0.0.252:9092,INTERNET://13.233.208.127:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNET:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  kafka2:
    image: confluentinc/cp-kafka
    hostname: kafka2
    depends_on:
      - zookeeper
    restart: "no"
    ports:
      - "9094:9094"
      - "9095:9095"
    volumes:
      - ./kafka/2/data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:39092,EXTERNAL://:9094,INTERNET://:9095"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:39092,EXTERNAL://10.0.0.252:9094,INTERNET://13.233.208.127:9095"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNET:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  kafka3:
    image: confluentinc/cp-kafka
    hostname: kafka3
    depends_on:
      - zookeeper
    restart: "no"
    ports:
      - "9096:9096"
      - "9097:9097"
    volumes:
      - ./kafka/3/data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:49092,EXTERNAL://:9096,INTERNET://:9097"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka3:49092,EXTERNAL://10.0.0.252:9096,INTERNET://13.233.208.127:9097"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNET:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
