version: "3"

services:
    redis:
        container_name: redis
        image: redis:alpine
        command: redis-server /user/local/etc/redis/redis.conf --requirepass mypassword
        ports:
            - "6379:6379"
        volumes:
            - $PWD/redis.conf:/user/local/etc/redis/redis.conf
    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: "no"
        ports:
            - "9000:9000"
        environment:
            KAFKA_BROKERCONNECT: "kafka1:29092,kafka2:39092,kafka3:49092"
            JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        depends_on:
            - "redis"
            - "kafka1"
            - "kafka2"
            - "kafka3"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/"]
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 60s
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:
            - ./zookeeper/data:/var/lib/zookeeper/data
            - ./zookeeper/log:/var/lib/zookeeper/log
    kafka1:
        image: confluentinc/cp-kafka
        hostname: kafka1
        depends_on:
            - zookeeper
        restart: "no"
        ports:
            - "9092:9092"
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_RESTART_ATTEMPTS: "10"
            KAFKA_RESTART_DELAY: "5"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    kafka2:
        image: confluentinc/cp-kafka
        hostname: kafka2
        depends_on:
            - zookeeper
        restart: "no"
        ports:
            - "9094:9094"
            - 39092:39092
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:39092,EXTERNAL://:9094
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:39092,EXTERNAL://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_RESTART_ATTEMPTS: "10"
            KAFKA_RESTART_DELAY: "5"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    kafka3:
        image: confluentinc/cp-kafka
        hostname: kafka3
        depends_on:
            - zookeeper
        restart: "no"
        ports:
            - "9096:9096"
            - 49092:49092
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:49092,EXTERNAL://:9096
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:49092,EXTERNAL://localhost:9096
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_RESTART_ATTEMPTS: "10"
            KAFKA_RESTART_DELAY: "5"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
